[function.main]
locals = ["struct"]
instructions = [
    { struct = {test_struct = {}} },
    { test = [{struct = {}}] }
]

[function.test] 
arguments = ["test"]
instructions = [
    { println = [{test = {}}, " test"] }
]

[struct.test_struct]
value = 5